export { default as Navigation } from "./section/static/navigation/index";
export { default as Footer } from "./section/static/footer/index";
export { default as About } from "./section/about/index";
export { default as Skills } from "./section/skills/index";
export { default as Projects } from "./section/projects/index";
export { default as Theme } from "./common/buttons/theme/index";
export { default as Language } from "./common/buttons/language/index";
export { default as Music } from "./common/buttons/music/index";
export { default as SkillsIcon } from "./common/skills-icon/index";
