name: Update and Restart App on DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  update-and-restart:
    runs-on: "ubuntu-latest"
    steps:
      - name: Update packages
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Create NVM directory
        run: mkdir $HOME/.nvm

      - name: Set NVM_DIR environment variable
        run: echo 'export NVM_DIR="$HOME/.nvm"' >> $HOME/.bashrc

      - name: Install nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
        creates: "$HOME/.nvm/nvm.sh"

      - name: Install node
        run: |
          source $HOME/.nvm/nvm.sh
          nvm install 16.6.2
        creates: "$HOME/.nvm/versions/node/v16.6.2/bin/node"

      - name: Install yarn
        run: |
          source $HOME/.nvm/nvm.sh
          npm install -g yarn
        creates: "$HOME/.nvm/versions/node/v16.6.2/bin/yarn"

      - name: Install pm2
        run: |
          source $HOME/.nvm/nvm.sh
          npm install -g pm2
        creates: "$HOME/.nvm/versions/node/v16.6.2/bin/pm2"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SSH into server and pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /${{ secrets.USER }}/projects/Portfolio-Next
            git pull origin main
            yarn build
            pm2 restart portfolio
