name: Update and Restart App on DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  update-and-restart:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SSH into server, pull and restart app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /${{ secrets.USER }}/projects/Portfolio-Next
            git pull origin main
            sudo apt-get install curl -y
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  
            nvm install --lts
            nvm use --lts
            npm install -g pm2
            pm2 stop all
            docker stop $(docker ps -aq)
            npm run build
            docker start $(docker ps -aq)
            pm2 restart all
