name: Update and Restart App on DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  update-and-restart:
    runs-on: "ubuntu-latest"
    steps:
      - name: Update packages
        run: sudo apt-get update && sudo apt-get install -y

      - name: Install nvm
        ansible.builtin.shell: >
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
        args:
          creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

      - name: Install node
        ansible.builtin.shell: >
          source ~/.nvm/nvm.sh && nvm install 16.6.2
        args:
          creates: "{{ ansible_env.HOME }}/.nvm/versions/node/v16.6.2/bin/node"

      - name: Install yarn
        ansible.builtin.shell: >
          source ~/.nvm/nvm.sh && npm install -g yarn
        args:
          creates: "{{ ansible_env.HOME }}/.nvm/versions/node/v16.6.2/bin/yarn"

      - name: Install pm2
        ansible.builtin.shell: >
          source ~/.nvm/nvm.sh && npm install -g pm2
        args:
          creates: "{{ ansible_env.HOME }}/.nvm/versions/node/v16.6.2/bin/pm2"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SSH into server and pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /${{ secrets.USER }}/projects/Portfolio-Next
            git pull origin main
            yarn build
            pm2 restart portfolio
